ARG version=9
FROM almalinux:${version}
ARG Course="Devops with Raju" \
    duration="120hrs"
ENV duration=${duration}
RUN echo "Course: ${Course}, duration: ${duration}, version: ${version}"
CMD ["sleep", "200"]